13192 flu form can submit no attachments
NYCPlanning/labs-applicant-portal pull request #828
Opened 2020-10-29 17:50 UTC by dhochbaum-dcp

### Summary

#### Task/Bug Number

### Technical Explanation

2020-10-29 19:35 UTC, allthesignals commented
@dhochbaum-dcp great! plz fix tests and make a full new PR. thanks for doing this so quickly!

2020-11-09 20:58 UTC, allthesignals commented
Why is this still open? Can you please fix the conflicts @dhochbaum-dcp?

2020-11-09 21:18 UTC, dhochbaum-dcp commented
> Why is this still open? Can you please fix the conflicts @dhochbaum-dcp?

Conflicts have been fixed.  Can you please review, so I can merge?

2020-11-09 21:38 UTC, godfreyyeung requested changes

2020-11-09 21:38 UTC, godfreyyeung commented on client/app/components/packages/landuse-form/edit.hbs
> +  @validators={{array (hash) this.validations.SubmittablePackageFormValidations}}
This shouldn't be reverted to (hash). `this.validations.SaveableLanduseFormValidations ` is useful and necessary

2020-11-09 21:39 UTC, godfreyyeung commented on client/app/components/packages/landuse-form/edit.hbs
> +  @validators={{array (hash) this.validations.SubmittablePackageFormValidations}}
Oops my mistake, wrong form

2020-11-09 21:41 UTC, godfreyyeung commented on client/tests/acceptance/user-can-click-landuse-form-edit-test.js
> +  // waitFor,
You should just delete this instead of commenting it out

2020-11-09 21:42 UTC, godfreyyeung commented on client/tests/acceptance/user-can-click-landuse-form-edit-test.js
> +    // assert.dom('[data-test-submit-button]').hasNoAttribute('disabled');
Either restore this or delete instead of commenting out

2020-11-09 21:42 UTC, godfreyyeung commented on client/tests/acceptance/user-can-click-landuse-form-edit-test.js
> +    // assert.dom('[data-test-section="attachments"]').exists();
Ditto for all these comments. They should either be restored or deleted

2020-11-09 21:44 UTC, godfreyyeung requested changes
Thank you!!! Please just restore, fix, or delete the commented lines in the test file.
If you delete, make sure it doesn't drop coverage though. Then it should be good

2020-11-09 22:15 UTC, dhochbaum-dcp commented
> Thank you!!! Please just restore, fix, or delete the commented lines in the test file.
> If you delete, make sure it doesn't drop coverage though. Then it should be good

Done, please approve so I can merge.

2020-11-10 19:13 UTC, allthesignals approved these changes

2020-11-10 19:14 UTC, allthesignals commented
Thanks @dhochbaum-dcp! I think you should ping people on Teams to get their attention faster.

2020-11-10 19:14 UTC, merged